substitutions:
  name: t-display-udp
  friendly_name: T-Display UDP Test

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.spi-test
    version: "1.1"
  platformio_options:
    build_unflags: -Werror=all
    board_build.flash_mode: dio


external_components:
 - source: github://clydebarrow/esphome@lvgl
   components: [ lvgl ] 
 - source: github://clydebarrow/esphome@i8080
   refresh: 10min
   components: [ i80, io_bus, ili9xxx, spi ] 

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    #type: arduino
    type: esp-idf

logger:
  level: VERBOSE
  logs:
    lvgl: WARN

#wifi: !include wifi.yaml

wifi:
  ap:
    manual_ip:
      static_ip: 10.1.1.250
      gateway: 10.1.1.1
      subnet: 255.255.252.0
      
    

#api:

#ota:

power_supply:
  - id: backlight
    enable_on_boot: true
    pin: GPIO38
  - id: lcd_pwr
    enable_on_boot: true
    pin: GPIO15

i80:
  dc_pin: 7
  wr_pin: 8
  rd_pin: 9
  data_pins: 
    - 39
    - 40
    - 41
    - 42
    -
      ignore_strapping_warning: true
      number: 45
    -
      ignore_strapping_warning: true
      number: 46
    - 47
    - 48
  

i2c:
  sda: 17
  scl: 18

psram:
  speed: 80MHz
  mode: octal

display:
  - platform: ili9xxx
    bus_type: i80
    cs_pin: 6
    reset_pin: 5
    id: w32_disp
    model: st7789v
    data_rate: 2MHz
    dimensions:
      height: 320
      width: 170
      offset_width: 35
      offset_height: 0
    transform:
      mirror_y: false
      mirror_x: false
      swap_xy: false
    color_order: bgr
    invert_colors: true
    auto_clear_enabled: false
    update_interval: never

packages:
  lvgl: !include lvgl-package.yaml

lvgl:
  displays: w32_disp


