esphome:
  name: guition-4848s040

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      execute_from_psram: false

external_components:
  - source: github://pr#9907
    components: [esp32]
    refresh: 1h

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG
  hardware_uart: uart0

debug:

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    psram:
      name: "Free PSRAM"

i2c:
  - id: bus_a
    sda: GPIO19
    scl:
      number: GPIO45
      ignore_strapping_warning: true

spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

output:
  - platform: ledc
    pin: GPIO38
    id: backlight_output
    frequency: 200Hz
    min_power: 50%

light:
  - platform: monochromatic
    output: backlight_output
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 5s
    gamma_correct: 1.8

touchscreen:
  platform: gt911

display:
  - platform: mipi_rgb
    model: GUITION-4848S040
    rotation: 180


lvgl:
