substitutions:
  name: lilygo-t-panel-s3
  friendly_name: Lilygo T-Panel S3

esphome:
  name: "${name}"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: github://pr#9892
    components: [mipi, mipi_rgb]
    refresh: 1h

logger:

psram:
  speed: 80MHz

i2c:
  - id: tp_i2c
    sda: 17
    scl: 18
    scan: true
    frequency: 400kHz

xl9535:
  id: expander

#touchscreen:
  #- platform: gt911
    #i2c_id: tp_i2c
    #id: my_touchscreen
    #update_interval: 16ms

light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: lcd_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    gamma_correct: 1.0

spi:
  - id: lcd_spi
    interface: software
    mosi_pin:
      xl9535:
      number: 16
    clk_pin:
      xl9535:
      number: 15

output:
  - platform: ledc
    id: backlight_output
    pin: 14
    frequency: 1220Hz
    inverted: false
    min_power: 15%

display:
  - platform: mipi_rgb
    model: t-panel-s3

lvgl:
