substitutions:
  name: lilygo-t-rgb-2-1
  friendly_name: Lilygo T-RGB-2.1

esphome:
  name: "${name}"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

#external_components:
  #- source: github://pr#9892
    #components: [mipi, mipi_rgb]
    #refresh: 1h

logger:

psram:
  mode: octal
  speed: 80MHz

i2c:
  - id: tp_i2c
    sda: 8
    scl: 48
    scan: true
    frequency: 400kHz

xl9535:
  id: expander

touchscreen:
  - platform: cst816
    reset_pin:
      xl9535: expander
      number: 1
    update_interval: 16ms
    skip_probe: true
    interrupt_pin: 1
    on_touch:
      logger.log:
        format: "Touch at %d/%d"
        args: [touch.x, touch.y]

light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: lcd_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    gamma_correct: 1.0

spi:
  - id: lcd_spi
    interface: software
    mosi_pin:
      xl9535:
      number: 4
    clk_pin:
      xl9535:
      number: 5

output:
  - platform: ledc
    id: backlight_output
    pin: 46
    frequency: 1220Hz
    inverted: false
    min_power: 15%

display:
  - platform: mipi_rgb
    model: t-rgb-2.1

lvgl:
