---
esphome:
  name: esp32-s3-box
  friendly_name: ESP32 S3 Box

esp32:
  variant: esp32s3

logger:

psram:
  mode: octal
  speed: 80MHz

binary_sensor:
  - platform: gt911
    id: touch_key_911
    index: 0
    name: Touch Button

i2c:
  - scl: 18
    sda: 8
    frequency: 400kHz

spi:
  mosi_pin: 6
  clk_pin: 7

touchscreen:
  - platform: gt911
    interrupt_pin:
      number: GPIO3
      ignore_strapping_warning: true

display:
  - platform: mipi_spi
    id: lcd_display
    model: s3box
    enable_pin: 47 # backlight
    reset_pin:
      inverted: true
      number: 48

lvgl:
