esphome:
  name: t-amoled

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

binary_sensor:
  - platform: cst816
    id: cst816_sensor
    on_click:
      - logger.log: Sensor clicked

spi:
  id: quad_spi
  type: quad
  clk_pin: 47
  data_pins: [ 18 , 7 , 48 , 5 ]

i2c:
  sda: 3
  scl: 2
  
touchscreen:
  - platform: cst816
    id: my_touchscreen
    interrupt_pin:
      number: 21
    on_update:
      then:
        lambda: |-
          for (auto touch : touches) {
            esph_log_d("touch", "%d: %d/%d", touch.id, touch.x, touch.y);
          }
display:
  - platform: mipi_spi
    #model: custom
    #model: rm67162
    model: t-display-s3-amoled
    id: main_lcd
    cs_pin: 6
    reset_pin: 17
    enable_pin: 38
    rotation: 90

psram:
  mode: octal
  speed: 80MHz

lvgl:
