esphome:
  name: t-amoled

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:

binary_sensor:
  - platform: touchscreen
    id: cst816_sensor
    on_click:
      - logger.log: Sensor clicked
    x_min: 0
    x_max: 240
    y_min: 537
    y_max: 600
    use_raw: true

spi:
  id: quad_spi
  type: quad
  clk_pin: 47
  data_pins: [ 18 , 7 , 48 , 5 ]

i2c:
  sda: 3
  scl: 2
  
touchscreen:
  - platform: cst816
    id: my_touchscreen
    transform:
      mirror_x: true
      mirror_y: false
      swap_xy: true
    interrupt_pin:
      number: 21
    on_update:
      then:
        lambda: |-
          for (auto touch : touches) {
            esph_log_d("touch", "%d: %d/%d", touch.id, touch.x, touch.y);
          }
display:
  - platform: mipi_spi
    model: t-display-s3-amoled
    id: main_lcd

lvgl:
