substitutions:
  name: esp32-2424s012
  friendly_name: Guition ESP32-2424S012

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  variant: esp32c3
  #cpu_frequency: 160MHz
  framework:
    type: esp-idf

logger:
  level: debug

debug:

spi:
  mosi_pin: GPIO7
  clk_pin: GPIO6

display:
  - platform: mipi_spi
    enable_pin: 3 # backlight
    id: display_id
    model: gc9a01a
    invert_colors: true
    buffer_size: 25%
    cs_pin: GPIO10
    dc_pin:
      number: GPIO2
      ignore_strapping_warning: true
    rotation: 90

i2c:
  scl: 5
  sda: 4


#touchscreen:
  #- platform: cst816
    #interrupt_pin: 0
    #reset_pin: 1
    
#lvgl:
