esphome:
  name: guition-4848s040

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      execute_from_psram: false

external_components:
  - source: github://pr#9907
    components: [esp32]
    refresh: 1h

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG
  hardware_uart: uart0

debug:

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    psram:
      name: "Free PSRAM"

i2c:
  - id: bus_a
    sda: GPIO19
    scl:
      number: GPIO45
      ignore_strapping_warning: true

spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

output:
  - platform: ledc
    pin: GPIO38
    id: backlight_output
    frequency: 200Hz
    min_power: 50%

light:
  - platform: monochromatic
    output: backlight_output
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 5s
    gamma_correct: 1.8

touchscreen:
  platform: gt911

display:
  - platform: mipi_rgb
    model: GUITION-4848S040
    rotation: 180

#  - platform: st7701s
#    spi_mode: MODE3
#    data_rate: 2MHz
#    color_order: RGB
#    invert_colors: False
#    dimensions:
#      width: 480
#      height: 480
#    transform:
#      mirror_x: false
#      mirror_y: true
#    cs_pin: 39
#    de_pin: 18
#    hsync_pin: 16
#    vsync_pin: 17
#    pclk_pin: 21
#    pclk_frequency: 12MHz
#    pclk_inverted: False
#    hsync_pulse_width: 8
#    hsync_front_porch: 10
#    hsync_back_porch: 20
#    vsync_pulse_width: 8
#    vsync_front_porch: 10
#    vsync_back_porch: 10
#    init_sequence:
#      - 1
#      # Custom sequences are an array, first byte is command, the rest are data.
#      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x10 ] # CMD2_BKSEL_BK0
#      - [ 0xCD, 0x00 ] # disable MDT flag
#    data_pins:
#      red:
#        - 11        #r1
#        - 12        #r2
#        - 13        #r3
#        - 14        #r4
#        - 0         #r5
#      green:
#        - 8         #g0
#        - 20        #g1
#        - 3         #g2
#        - 46        #g3
#        - 9         #g4
#        - 10        #g5
#      blue:
#        - 4         #b1
#        - 5         #b2
#        - 6         #b3
#        - 7         #b4
#        - 15        #b5
#    show_test_card: true
