substitutions:
  name: ili9481
  friendly_name: ILI9481 Lily Pi

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

psram:
  speed: 80MHz

i2c:
  sda: 21
  scl: 22

touchscreen:
  - platform: gt911
    id: my_touchscreen
    #interrupt_pin: 34
    update_interval: 16ms
    transform:
      swap_xy: true
      mirror_x: true
    on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );

output:
  - platform: ledc
    pin:
      number: GPIO12
      ignore_strapping_warning: true
    id: gpio_32_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_32_backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

display:
  - platform: mipi_spi
    data_rate: 80MHz
    model: ili9481
    init_sequence:
    invert_colors: true
    dc_pin: GPIO27
    show_test_card: true
    rotation: 270
    cs_pin:
      number: GPIO5
      ignore_strapping_warning: true
