---
esphome:
  name: esp32-s3-box
  friendly_name: ESP32 S3 Box

esp32:
  board: esp32s3box
  framework:
    type: esp-idf

logger:

psram:
  mode: octal
  speed: 80MHz

binary_sensor:
  - platform: gt911
    id: touch_key_911
    index: 0
    name: Touch Button

i2c:
  - scl: 18
    sda: 8
    id: i2c_onboard
    frequency: 400kHz

spi:
  mosi_pin: 6
  clk_pin: 7
  interface: hardware

display:
  - platform: mipi_spi
    id: lcd_display
    model: s3box

power_supply:
  - pin: 47
    id: backlight
    enable_on_boot: true

touchscreen:
  - platform: gt911
    display: lcd_display
    id: gt911_touchscreen
    interrupt_pin:
      number: GPIO3
      ignore_strapping_warning: true

