substitutions:
  name: seed-d1001
  friendly_name: Seeed Studio D1001

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-p4-evboard
  flash_size: 16MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes
      execute_from_psram: true


logger:
  level: debug

psram:
  speed: 200MHz

debug:

api:

esp_ldo:
  - channel: 3
    voltage: 2.5V

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

ota:
  - platform: esphome

wifi: !include wifi.yaml

display:
  - platform: mipi_dsi
    model: WAVESHARE-P4-NANO-10.1
    rotation: 90

i2c:
  sda: GPIO7
  scl: GPIO8
  frequency: 400kHz
    

touchscreen:
  - platform: gt911
    id: touchscreen_
    transform:
      swap_xy: true
      mirror_y: true
      mirror_x: false

