substitutions:
  name: st7735-c3
  friendly_name: ST7735 on C3

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

logger:
  level: DEBUG

power_supply:
  - pin: GPIO0
    id: backlight_output
    enable_on_boot: true

sensor:
  - platform: internal_temperature
    name: "ESP32 temperature"

spi:
  mosi_pin:
    number: GPIO2
    ignore_strapping_warning: true
  clk_pin: GPIO1

display:
  - platform: mipi_spi
    id: display_id
    model: st7735
    cs_pin:
      number: GPIO8
      ignore_strapping_warning: true
    dc_pin:
      number: GPIO3
    reset_pin:
      number: GPIO4
    show_test_card: true

