esphome:
  name: t-display-s3

esp32:
  variant: esp32s3

logger:

output:
  - platform: ledc
    frequency: 9765Hz
    pin: GPIO38
    id: backlight_output

light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: led
    restore_mode: ALWAYS_ON
    default_transition_length: 0s

spi:
  type: octal
  clk_pin: 8
  data_pins: 
    - 39
    - 40
    - 41
    - 42
    - ignore_strapping_warning: true
      number: 45
    - ignore_strapping_warning: true
      number: 46
    - 47
    - 48
  
psram:
  speed: 80MHz
  mode: octal

external_components:
  - source: github://pr#17247
    components: [mipi_spi]
    refresh: 1h
display:
  - platform: mipi_spi
    model: t-display-s3
