# For Waveshare 4.3

esphome:
  name: wave-4-3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y


logger:
  level: verbose

psram:
  mode: octal
  speed: 80MHz

i2c:
  sda: 8
  scl: 9
  frequency: 400kHz
  scan: false
  id: bus_a


touchscreen:
  - platform: gt911
    address: 0x5D
    id: my_touchscreen
    update_interval: 16ms
    interrupt_pin: 4
    reset_pin:
      ch422g:
      number: 1

display:
  - platform: mipi_rgb
    model: ESP32-S3-Touch-LCD-4.3
    id: rpi_disp

ch422g:

