---
esphome:
  name: esp32-s3-box
  friendly_name: ESP32 S3 Box
  platformio_options:
    upload_speed: 921600
  project:
    name: esphome.voice-assistant
    version: "1.0"
  #min_version: 2023.11.0b5

esp32:
  board: esp32s3box
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_160: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

logger:

psram:
  mode: octal
  speed: 80MHz

binary_sensor:
  - platform: gt911
    id: touch_key_911
    index: 0
    name: Touch Button

i2c:
  - scl: 18
    sda: 8
    id: i2c_onboard

spi:
  mosi_pin: 6
  clk_pin: 7
  interface: hardware

display:
  - platform: mipi_spi
    id: lcd_display
    model: s3box

power_supply:
  - pin: 47
    id: backlight
    enable_on_boot: true

touchscreen:
  - platform: gt911
    display: lcd_display
    id: gt911_touchscreen
    interrupt_pin:
      number: GPIO3
      ignore_strapping_warning: true

lvgl:
