
#-------------------------------------------
substitutions:
  name: lilygo-t-rgb-2-1
  friendly_name: Lilygo T-RGB 2.1in

esphome:
  name: "${name}"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

logger:


psram:
  mode: octal
  speed: 80MHz

i2c:
  - id: tp_i2c
    sda: 8
    scl: 48
    scan: true
    frequency: 400kHz

xl9535:
  id: expander

power_supply:
  - id: pwr_en
    pin:
      xl9535: expander
      number: 2
    enable_on_boot: true
  - id: lcd_bl
    pin:
      number: 46
    enable_on_boot: true

touchscreen:
  - platform: cst816
    id: my_touchscreen
    reset_pin:
      xl9535: expander
      number: 1
    update_interval: 16ms
    skip_probe: true
    interrupt_pin: 1
    on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );

#output:
#  - platform: ledc
#    id: backlight_output
#    pin: 46
#    frequency: 1220Hz
#    inverted: true
#    min_power: 15%
#
#light:
#  - platform: monochromatic
#    output: backlight_output
#    name: LCD Backlight
#    id: lcd_backlight
#    restore_mode: ALWAYS_ON
#    default_transition_length: 0s
#    gamma_correct: 1.8

spi:
  - id: lcd_spi
    clk_pin:
      xl9535: expander
      number: 5
    mosi_pin:
      xl9535: expander
      number: 4
    interface: software
    
display:
  - platform: st7701s
    id: st7701s_disp
    update_interval: never
    auto_clear_enabled: false
    data_rate: 75kHz
    spi_mode: MODE3
    color_order: BGR
    invert_colors: true
    dimensions:
      width: 480
      height: 480
    transform:
      mirror_x: false
      mirror_y: false
    cs_pin:
      xl9535: expander
      number: 3
    de_pin: GPIO45
    hsync_pin: GPIO47
    vsync_pin: GPIO41
    pclk_pin: GPIO42
    pclk_frequency: 12MHz
    pclk_inverted: false
#
    data_pins:
      red:
        - GPIO2       #r1
        - GPIO3       #r2
        - GPIO5       #r3
        - GPIO6       #r4
        - GPIO7       #r5
      green:
        - GPIO9       #g0
        - GPIO10       #g1
        - GPIO11       #g2
        - GPIO12       #g3
        - GPIO13       #g4
        - GPIO14     #g5
      blue:
        - GPIO15       #b1
        - GPIO16       #b2
        - GPIO17       #b3
        - GPIO18       #b4
        - GPIO21       #b5`

lvgl:
