esphome:
  name: wt32-sc01-plus

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

logger:

power_supply:
  - id: backlight
    enable_on_boot: true
    pin:
      ignore_strapping_warning: true
      number: GPIO45

i2c:
  frequency: 400kHz
  sda: 6
  scl: 5

touchscreen:
  - platform: ft63x6
    id: my_touchscreen
    interrupt_pin: 7

psram:
  speed: 80MHz

external_components:
  - source: github://clydebarrow/esphome@mipi-spi
    components: [spi, mipi_spi]
    refresh: 1h

spi:
  - type: octal
    id: octal_spi
    clk_pin: 47
    data_pins: 
      - 9
      - ignore_strapping_warning: true
        number: 46
      - ignore_strapping_warning: true
        number: 3
      - 8
      - 18
      - 17
      - 16
      - 15
  

display:
  - platform: mipi_spi
    id: w32_disp
    model: wt32-sc01-plus
    data_rate: 10MHz
    rotation: 90

lvgl:
